name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.x
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"
                  architecture: "x64"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install beautifulsoup4
           - uses: allenevans/set-env@v1.0.0
           - name: set environment variables
             with:
                 NOTFOLLOWING: 'None'
                 NEEDTOFOLLOW: 'None'
            - name: Crosscheck followers
              run: |
                  echo "##[set-output name=notf;]$(python main.py --notf)"
                  echo "##[set-output name=needf;]$(python main.py --needf)"
                  run: echo '::set-env name=NOTFOLLOWING::$steps.checker.outputs.notf'
                  run: echo '::set-env name=NEEDTOFOLLOW::$steps.checker.outputs.needf'
              id: checker
            - if: steps.checker.outputs.notf != "None"
            - uses: JasonEtco/create-an-issue@v2
            - name: Create issue if someone has unfollowed
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  notf: $NOTFOLLOWING
              with:
                  filename: .github/notf.md
            - if: steps.checker.outputs.needf != "None"
            - uses: JasonEtco/create-an-issue@v2
            - name: Create issue if someone has followed
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  needf: $NEEDTOFOLLOW
              with:
                  filename: .github/notf.md