name: Followback Checker

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: set environment variables
              uses: allenevans/set-env@v1.0.0
              with:
                  NOTFOLLOWING: "None"
                  NEEDTOFOLLOW: "None"

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"
                  architecture: "x64"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install beautifulsoup4

            - name: Check Not Following
              run: |
                  echo ::set-env name=NOTFOLLOWING::$(python main.py --notf)
                  echo '::set-env name=notf::$NOTFOLLOWING'
              id: cnotf
            - name: Check Need to Follow
              run: |
                  echo ::set-env name=NEEDTOFOLLOW::$(python main.py --needf)
                  echo '::set-env name=needf::$NEEDTOFOLLOW'
              id: cneedf
            - name: Print Follow Details
              run: |
                  echo "NOTFOLLOWING=${NOTFOLLOWING}"
                  echo "NEEDTOFOLLOW=${NEEDTOFOLLOW}"

            - if: ${{steps.cneedf.outputs.needf != "None"}}
              name: Create issue if someone has unfollowed
              run: echo "Test"
            #   uses: JasonEtco/create-an-issue@v2
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       notf: $NOTFOLLOWING
            #   with:
            #       filename: .github/notf.md
            # - if: steps.checker.outputs.needf != "None"
            # - name: Create issue if someone has followed
            #   uses: JasonEtco/create-an-issue@v2
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       needf: $NEEDTOFOLLOW
            #   with:
            #       filename: .github/notf.md
